services:
  expo-app:
    build:
      context: .
    environment:
      - NODE_ENV=
      - CHOKIDAR_USEPOLLING=true
      - EXPO_TUNNEL_URL=exp://192.168.0.112:19000
      - WEB_HOST=0.0.0.0
      - EXPO_PACKAGER_HOSTNAME=0.0.0.0
    tty: true
    stdin_open: true
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - .:/app
      - notused:/app/node_modules

volumes:
  notused:
